# Generated by Django 2.2.24 on 2022-08-17 07:29
import datetime

from django.db import migrations


def set_new_or_old_builders(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    all_flats = Flat.objects.all()
    for flat in all_flats:
        if flat.construction_year >= 2015:
            flat.new_building = True
            flat.save()
        else:
            flat.new_building = False
            flat.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(set_new_or_old_builders)
    ]
