# Generated by Django 2.2.24 on 2022-08-17 08:53

from django.db import migrations


def copy_flats_from_flat_to_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    owners = Owner.objects.all()
    for owner in owners:
        owner_flats = Flat.objects.filter(owner=owner)
        for owner_flat in owner_flats:
            Owner.objects.update_or_create(flats=owner_flat)
            Owner.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0010_auto_20220817_1131'),
    ]

    operations = [
        migrations.RunPython(copy_flats_from_flat_to_owner)
    ]
