# Generated by Django 2.2.24 on 2022-08-20 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20220820_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='date',
            new_name='created_at',
        ),
    ]
