# Generated by Django 2.2.24 on 2022-08-21 08:24

from django.db import migrations


def copy_flats_from_flat_to_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    owners = Owner.objects.all()
    for owner in owners.iterator():
        owner_flats = Flat.objects.filter(pure_phone=owner.pure_phone)
        owner.flats.set(owner_flats)
        owner.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0014_auto_20220820_1120'),
    ]

    operations = [
        migrations.RunPython(copy_flats_from_flat_to_owner)
    ]
