# Generated by Django 4.1 on 2022-08-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20220821_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='pure_phone',
        ),
        migrations.AlterField(
            model_name='flat',
            name='has_balcony',
            field=models.BooleanField(db_index=True, null=True, verbose_name='Наличие балкона'),
        ),
    ]
