# Generated by Django 4.1 on 2022-08-31 08:26

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_remove_flat_pure_phone_alter_complaint_flat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Нормализованный номер владельца'),
        ),
    ]
