# Generated by Django 4.1 on 2022-08-31 08:43

from django.db import migrations
import phonenumbers


def copy_phones_to_pure_phones(apps, schema):
    Owner = apps.get_model('property', 'Owner')
    owners = Owner.objects.all()
    for owner in owners.iterator():
        owner.pure_phone = phonenumbers.parse(owner.phonenumber, 'RU')
        owner.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0019_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(copy_phones_to_pure_phones)
    ]
